#!/bin/zsh
rm mod.rs 2>&-

for file in *.rs; do
    if [ "$file" != "mod.rs" ]; then
        module_name=$(basename "$file" .rs)
        echo "pub mod $module_name;" >> mod.rs
    fi
done

if [[ $? == 0 ]]; then
    echo "Success: created a mod.rs in $(pwd) with:"
    echo "$(cat mod.rs)"
else
    echo "Failed to create mod.rs in $(pwd)!"
fi
