#!/bin/zsh

# Get the network service name for the DL-dock
DOCK_SERVICE="DL-Dock" 
# look up if dock provided ip address
IP_ADDR=$(/usr/sbin/networksetup -getinfo "$DOCK_SERVICE" | grep "IP address" | awk '{print $NF}')

echo "ip addr found is: $IP_ADDR"

# Check if the network service is connected
if [[ $IP_ADDR != 'none' ]]; then
    # If connected, disable Wi-Fi
    networksetup -setairportpower en0 off
else
    # If not connected, enable Wi-Fi
    networksetup -setairportpower en0 on
fi
